# Generated by Django 5.1.1 on 2024-12-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['quantity', 'product__price'], 'verbose_name': 'Artículo en carrito', 'verbose_name_plural': 'Artículos en carrito'},
        ),
    ]
