# Generated by Django 5.1.1 on 2024-10-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_alter_cartitem_cart_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cartitem')),
            ],
        ),
    ]
