# Generated by Django 5.1.1 on 2024-10-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart_alter_cartitem_quantity'),
        ('orders', '0003_remove_order_cart_item_order_cart'),
        ('users', '0002_addressuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cart.cartitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='users.addressuser'),
        ),
    ]
