# Generated by Django 5.1.1 on 2024-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Órden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
    ]
