# Generated by Django 5.1.1 on 2024-12-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['quantity', 'product__price'], 'verbose_name': 'Artículo en órden de compra', 'verbose_name_plural': 'Artículos en órden de compra'},
        ),
    ]
