# Generated by Django 5.1.4 on 2024-12-12 13:42

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/images/', validators=[catalog.validators.validate_image], verbose_name='imagen'),
        ),
    ]
